# Generated by Django 4.1.4 on 2023-01-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
