# Generated by Django 4.1.4 on 2023-01-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='image',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Image pricipale'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(default='Non disponible', max_length=100, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Prix'),
        ),
    ]
