# Generated by Django 4.1.4 on 2023-02-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(default='ND', max_length=100, verbose_name='Contact'),
        ),
    ]
